//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.WSLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WSLogin.WSLOGIN")]
    public interface WSLOGIN {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Sacar_rutClienteRequest", ReplyAction="http://ws/WSLOGIN/Sacar_rutClienteResponse")]
        Vista.WSLogin.Sacar_rutClienteResponse Sacar_rutCliente(Vista.WSLogin.Sacar_rutClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Sacar_rutClienteRequest", ReplyAction="http://ws/WSLOGIN/Sacar_rutClienteResponse")]
        System.Threading.Tasks.Task<Vista.WSLogin.Sacar_rutClienteResponse> Sacar_rutClienteAsync(Vista.WSLogin.Sacar_rutClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/sacarIdPedidoRequest", ReplyAction="http://ws/WSLOGIN/sacarIdPedidoResponse")]
        Vista.WSLogin.sacarIdPedidoResponse sacarIdPedido(Vista.WSLogin.sacarIdPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/sacarIdPedidoRequest", ReplyAction="http://ws/WSLOGIN/sacarIdPedidoResponse")]
        System.Threading.Tasks.Task<Vista.WSLogin.sacarIdPedidoResponse> sacarIdPedidoAsync(Vista.WSLogin.sacarIdPedidoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/nombreClienteRequest", ReplyAction="http://ws/WSLOGIN/nombreClienteResponse")]
        Vista.WSLogin.nombreClienteResponse nombreCliente(Vista.WSLogin.nombreClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/nombreClienteRequest", ReplyAction="http://ws/WSLOGIN/nombreClienteResponse")]
        System.Threading.Tasks.Task<Vista.WSLogin.nombreClienteResponse> nombreClienteAsync(Vista.WSLogin.nombreClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        Vista.WSLogin.LoginResponse Login(Vista.WSLogin.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        System.Threading.Tasks.Task<Vista.WSLogin.LoginResponse> LoginAsync(Vista.WSLogin.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Cliente_activoRequest", ReplyAction="http://ws/WSLOGIN/Cliente_activoResponse")]
        Vista.WSLogin.Cliente_activoResponse Cliente_activo(Vista.WSLogin.Cliente_activoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Cliente_activoRequest", ReplyAction="http://ws/WSLOGIN/Cliente_activoResponse")]
        System.Threading.Tasks.Task<Vista.WSLogin.Cliente_activoResponse> Cliente_activoAsync(Vista.WSLogin.Cliente_activoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/correoCliRequest", ReplyAction="http://ws/WSLOGIN/correoCliResponse")]
        Vista.WSLogin.correoCliResponse correoCli(Vista.WSLogin.correoCliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/correoCliRequest", ReplyAction="http://ws/WSLOGIN/correoCliResponse")]
        System.Threading.Tasks.Task<Vista.WSLogin.correoCliResponse> correoCliAsync(Vista.WSLogin.correoCliRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sacar_rutClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sacar_rutCliente", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.Sacar_rutClienteRequestBody Body;
        
        public Sacar_rutClienteRequest() {
        }
        
        public Sacar_rutClienteRequest(Vista.WSLogin.Sacar_rutClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Sacar_rutClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public Sacar_rutClienteRequestBody() {
        }
        
        public Sacar_rutClienteRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sacar_rutClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sacar_rutClienteResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.Sacar_rutClienteResponseBody Body;
        
        public Sacar_rutClienteResponse() {
        }
        
        public Sacar_rutClienteResponse(Vista.WSLogin.Sacar_rutClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Sacar_rutClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public Sacar_rutClienteResponseBody() {
        }
        
        public Sacar_rutClienteResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sacarIdPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sacarIdPedido", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.sacarIdPedidoRequestBody Body;
        
        public sacarIdPedidoRequest() {
        }
        
        public sacarIdPedidoRequest(Vista.WSLogin.sacarIdPedidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sacarIdPedidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public sacarIdPedidoRequestBody() {
        }
        
        public sacarIdPedidoRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sacarIdPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sacarIdPedidoResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.sacarIdPedidoResponseBody Body;
        
        public sacarIdPedidoResponse() {
        }
        
        public sacarIdPedidoResponse(Vista.WSLogin.sacarIdPedidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sacarIdPedidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sacarIdPedidoResponseBody() {
        }
        
        public sacarIdPedidoResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombreClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombreCliente", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.nombreClienteRequestBody Body;
        
        public nombreClienteRequest() {
        }
        
        public nombreClienteRequest(Vista.WSLogin.nombreClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nombreClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public nombreClienteRequestBody() {
        }
        
        public nombreClienteRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombreClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombreClienteResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.nombreClienteResponseBody Body;
        
        public nombreClienteResponse() {
        }
        
        public nombreClienteResponse(Vista.WSLogin.nombreClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nombreClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public nombreClienteResponseBody() {
        }
        
        public nombreClienteResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Vista.WSLogin.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Vista.WSLogin.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cliente_activoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cliente_activo", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.Cliente_activoRequestBody Body;
        
        public Cliente_activoRequest() {
        }
        
        public Cliente_activoRequest(Vista.WSLogin.Cliente_activoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Cliente_activoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public Cliente_activoRequestBody() {
        }
        
        public Cliente_activoRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cliente_activoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cliente_activoResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.Cliente_activoResponseBody Body;
        
        public Cliente_activoResponse() {
        }
        
        public Cliente_activoResponse(Vista.WSLogin.Cliente_activoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Cliente_activoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public Cliente_activoResponseBody() {
        }
        
        public Cliente_activoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class correoCliRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="correoCli", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.correoCliRequestBody Body;
        
        public correoCliRequest() {
        }
        
        public correoCliRequest(Vista.WSLogin.correoCliRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class correoCliRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public correoCliRequestBody() {
        }
        
        public correoCliRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class correoCliResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="correoCliResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLogin.correoCliResponseBody Body;
        
        public correoCliResponse() {
        }
        
        public correoCliResponse(Vista.WSLogin.correoCliResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class correoCliResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public correoCliResponseBody() {
        }
        
        public correoCliResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLOGINChannel : Vista.WSLogin.WSLOGIN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLOGINClient : System.ServiceModel.ClientBase<Vista.WSLogin.WSLOGIN>, Vista.WSLogin.WSLOGIN {
        
        public WSLOGINClient() {
        }
        
        public WSLOGINClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLogin.Sacar_rutClienteResponse Vista.WSLogin.WSLOGIN.Sacar_rutCliente(Vista.WSLogin.Sacar_rutClienteRequest request) {
            return base.Channel.Sacar_rutCliente(request);
        }
        
        public string Sacar_rutCliente(string user, string pass) {
            Vista.WSLogin.Sacar_rutClienteRequest inValue = new Vista.WSLogin.Sacar_rutClienteRequest();
            inValue.Body = new Vista.WSLogin.Sacar_rutClienteRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLogin.Sacar_rutClienteResponse retVal = ((Vista.WSLogin.WSLOGIN)(this)).Sacar_rutCliente(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLogin.Sacar_rutClienteResponse> Vista.WSLogin.WSLOGIN.Sacar_rutClienteAsync(Vista.WSLogin.Sacar_rutClienteRequest request) {
            return base.Channel.Sacar_rutClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLogin.Sacar_rutClienteResponse> Sacar_rutClienteAsync(string user, string pass) {
            Vista.WSLogin.Sacar_rutClienteRequest inValue = new Vista.WSLogin.Sacar_rutClienteRequest();
            inValue.Body = new Vista.WSLogin.Sacar_rutClienteRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLogin.WSLOGIN)(this)).Sacar_rutClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLogin.sacarIdPedidoResponse Vista.WSLogin.WSLOGIN.sacarIdPedido(Vista.WSLogin.sacarIdPedidoRequest request) {
            return base.Channel.sacarIdPedido(request);
        }
        
        public int sacarIdPedido(string user, string pass) {
            Vista.WSLogin.sacarIdPedidoRequest inValue = new Vista.WSLogin.sacarIdPedidoRequest();
            inValue.Body = new Vista.WSLogin.sacarIdPedidoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLogin.sacarIdPedidoResponse retVal = ((Vista.WSLogin.WSLOGIN)(this)).sacarIdPedido(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLogin.sacarIdPedidoResponse> Vista.WSLogin.WSLOGIN.sacarIdPedidoAsync(Vista.WSLogin.sacarIdPedidoRequest request) {
            return base.Channel.sacarIdPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLogin.sacarIdPedidoResponse> sacarIdPedidoAsync(string user, string pass) {
            Vista.WSLogin.sacarIdPedidoRequest inValue = new Vista.WSLogin.sacarIdPedidoRequest();
            inValue.Body = new Vista.WSLogin.sacarIdPedidoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLogin.WSLOGIN)(this)).sacarIdPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLogin.nombreClienteResponse Vista.WSLogin.WSLOGIN.nombreCliente(Vista.WSLogin.nombreClienteRequest request) {
            return base.Channel.nombreCliente(request);
        }
        
        public string nombreCliente(string user, string pass) {
            Vista.WSLogin.nombreClienteRequest inValue = new Vista.WSLogin.nombreClienteRequest();
            inValue.Body = new Vista.WSLogin.nombreClienteRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLogin.nombreClienteResponse retVal = ((Vista.WSLogin.WSLOGIN)(this)).nombreCliente(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLogin.nombreClienteResponse> Vista.WSLogin.WSLOGIN.nombreClienteAsync(Vista.WSLogin.nombreClienteRequest request) {
            return base.Channel.nombreClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLogin.nombreClienteResponse> nombreClienteAsync(string user, string pass) {
            Vista.WSLogin.nombreClienteRequest inValue = new Vista.WSLogin.nombreClienteRequest();
            inValue.Body = new Vista.WSLogin.nombreClienteRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLogin.WSLOGIN)(this)).nombreClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLogin.LoginResponse Vista.WSLogin.WSLOGIN.Login(Vista.WSLogin.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string user, string pass) {
            Vista.WSLogin.LoginRequest inValue = new Vista.WSLogin.LoginRequest();
            inValue.Body = new Vista.WSLogin.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLogin.LoginResponse retVal = ((Vista.WSLogin.WSLOGIN)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLogin.LoginResponse> Vista.WSLogin.WSLOGIN.LoginAsync(Vista.WSLogin.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLogin.LoginResponse> LoginAsync(string user, string pass) {
            Vista.WSLogin.LoginRequest inValue = new Vista.WSLogin.LoginRequest();
            inValue.Body = new Vista.WSLogin.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLogin.WSLOGIN)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLogin.Cliente_activoResponse Vista.WSLogin.WSLOGIN.Cliente_activo(Vista.WSLogin.Cliente_activoRequest request) {
            return base.Channel.Cliente_activo(request);
        }
        
        public string Cliente_activo(string user, string pass) {
            Vista.WSLogin.Cliente_activoRequest inValue = new Vista.WSLogin.Cliente_activoRequest();
            inValue.Body = new Vista.WSLogin.Cliente_activoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLogin.Cliente_activoResponse retVal = ((Vista.WSLogin.WSLOGIN)(this)).Cliente_activo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLogin.Cliente_activoResponse> Vista.WSLogin.WSLOGIN.Cliente_activoAsync(Vista.WSLogin.Cliente_activoRequest request) {
            return base.Channel.Cliente_activoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLogin.Cliente_activoResponse> Cliente_activoAsync(string user, string pass) {
            Vista.WSLogin.Cliente_activoRequest inValue = new Vista.WSLogin.Cliente_activoRequest();
            inValue.Body = new Vista.WSLogin.Cliente_activoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLogin.WSLOGIN)(this)).Cliente_activoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLogin.correoCliResponse Vista.WSLogin.WSLOGIN.correoCli(Vista.WSLogin.correoCliRequest request) {
            return base.Channel.correoCli(request);
        }
        
        public string correoCli(string user, string pass) {
            Vista.WSLogin.correoCliRequest inValue = new Vista.WSLogin.correoCliRequest();
            inValue.Body = new Vista.WSLogin.correoCliRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLogin.correoCliResponse retVal = ((Vista.WSLogin.WSLOGIN)(this)).correoCli(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLogin.correoCliResponse> Vista.WSLogin.WSLOGIN.correoCliAsync(Vista.WSLogin.correoCliRequest request) {
            return base.Channel.correoCliAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLogin.correoCliResponse> correoCliAsync(string user, string pass) {
            Vista.WSLogin.correoCliRequest inValue = new Vista.WSLogin.correoCliRequest();
            inValue.Body = new Vista.WSLogin.correoCliRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLogin.WSLOGIN)(this)).correoCliAsync(inValue);
        }
    }
}
