//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.WEBServiceLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WEBServiceLogin.WSLOGIN")]
    public interface WSLOGIN {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        Vista.WEBServiceLogin.LoginResponse Login(Vista.WEBServiceLogin.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        System.Threading.Tasks.Task<Vista.WEBServiceLogin.LoginResponse> LoginAsync(Vista.WEBServiceLogin.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Sacar_rutClienteRequest", ReplyAction="http://ws/WSLOGIN/Sacar_rutClienteResponse")]
        Vista.WEBServiceLogin.Sacar_rutClienteResponse Sacar_rutCliente(Vista.WEBServiceLogin.Sacar_rutClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Sacar_rutClienteRequest", ReplyAction="http://ws/WSLOGIN/Sacar_rutClienteResponse")]
        System.Threading.Tasks.Task<Vista.WEBServiceLogin.Sacar_rutClienteResponse> Sacar_rutClienteAsync(Vista.WEBServiceLogin.Sacar_rutClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Cliente_activoRequest", ReplyAction="http://ws/WSLOGIN/Cliente_activoResponse")]
        Vista.WEBServiceLogin.Cliente_activoResponse Cliente_activo(Vista.WEBServiceLogin.Cliente_activoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/Cliente_activoRequest", ReplyAction="http://ws/WSLOGIN/Cliente_activoResponse")]
        System.Threading.Tasks.Task<Vista.WEBServiceLogin.Cliente_activoResponse> Cliente_activoAsync(Vista.WEBServiceLogin.Cliente_activoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ws/", Order=0)]
        public Vista.WEBServiceLogin.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Vista.WEBServiceLogin.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ws/", Order=0)]
        public Vista.WEBServiceLogin.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Vista.WEBServiceLogin.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sacar_rutClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sacar_rutCliente", Namespace="http://ws/", Order=0)]
        public Vista.WEBServiceLogin.Sacar_rutClienteRequestBody Body;
        
        public Sacar_rutClienteRequest() {
        }
        
        public Sacar_rutClienteRequest(Vista.WEBServiceLogin.Sacar_rutClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Sacar_rutClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public Sacar_rutClienteRequestBody() {
        }
        
        public Sacar_rutClienteRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sacar_rutClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sacar_rutClienteResponse", Namespace="http://ws/", Order=0)]
        public Vista.WEBServiceLogin.Sacar_rutClienteResponseBody Body;
        
        public Sacar_rutClienteResponse() {
        }
        
        public Sacar_rutClienteResponse(Vista.WEBServiceLogin.Sacar_rutClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Sacar_rutClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public Sacar_rutClienteResponseBody() {
        }
        
        public Sacar_rutClienteResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cliente_activoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cliente_activo", Namespace="http://ws/", Order=0)]
        public Vista.WEBServiceLogin.Cliente_activoRequestBody Body;
        
        public Cliente_activoRequest() {
        }
        
        public Cliente_activoRequest(Vista.WEBServiceLogin.Cliente_activoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Cliente_activoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public Cliente_activoRequestBody() {
        }
        
        public Cliente_activoRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cliente_activoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cliente_activoResponse", Namespace="http://ws/", Order=0)]
        public Vista.WEBServiceLogin.Cliente_activoResponseBody Body;
        
        public Cliente_activoResponse() {
        }
        
        public Cliente_activoResponse(Vista.WEBServiceLogin.Cliente_activoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Cliente_activoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public Cliente_activoResponseBody() {
        }
        
        public Cliente_activoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLOGINChannel : Vista.WEBServiceLogin.WSLOGIN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLOGINClient : System.ServiceModel.ClientBase<Vista.WEBServiceLogin.WSLOGIN>, Vista.WEBServiceLogin.WSLOGIN {
        
        public WSLOGINClient() {
        }
        
        public WSLOGINClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WEBServiceLogin.LoginResponse Vista.WEBServiceLogin.WSLOGIN.Login(Vista.WEBServiceLogin.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string user, string pass) {
            Vista.WEBServiceLogin.LoginRequest inValue = new Vista.WEBServiceLogin.LoginRequest();
            inValue.Body = new Vista.WEBServiceLogin.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WEBServiceLogin.LoginResponse retVal = ((Vista.WEBServiceLogin.WSLOGIN)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WEBServiceLogin.LoginResponse> Vista.WEBServiceLogin.WSLOGIN.LoginAsync(Vista.WEBServiceLogin.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WEBServiceLogin.LoginResponse> LoginAsync(string user, string pass) {
            Vista.WEBServiceLogin.LoginRequest inValue = new Vista.WEBServiceLogin.LoginRequest();
            inValue.Body = new Vista.WEBServiceLogin.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WEBServiceLogin.WSLOGIN)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WEBServiceLogin.Sacar_rutClienteResponse Vista.WEBServiceLogin.WSLOGIN.Sacar_rutCliente(Vista.WEBServiceLogin.Sacar_rutClienteRequest request) {
            return base.Channel.Sacar_rutCliente(request);
        }
        
        public string Sacar_rutCliente(string user, string pass) {
            Vista.WEBServiceLogin.Sacar_rutClienteRequest inValue = new Vista.WEBServiceLogin.Sacar_rutClienteRequest();
            inValue.Body = new Vista.WEBServiceLogin.Sacar_rutClienteRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WEBServiceLogin.Sacar_rutClienteResponse retVal = ((Vista.WEBServiceLogin.WSLOGIN)(this)).Sacar_rutCliente(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WEBServiceLogin.Sacar_rutClienteResponse> Vista.WEBServiceLogin.WSLOGIN.Sacar_rutClienteAsync(Vista.WEBServiceLogin.Sacar_rutClienteRequest request) {
            return base.Channel.Sacar_rutClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WEBServiceLogin.Sacar_rutClienteResponse> Sacar_rutClienteAsync(string user, string pass) {
            Vista.WEBServiceLogin.Sacar_rutClienteRequest inValue = new Vista.WEBServiceLogin.Sacar_rutClienteRequest();
            inValue.Body = new Vista.WEBServiceLogin.Sacar_rutClienteRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WEBServiceLogin.WSLOGIN)(this)).Sacar_rutClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WEBServiceLogin.Cliente_activoResponse Vista.WEBServiceLogin.WSLOGIN.Cliente_activo(Vista.WEBServiceLogin.Cliente_activoRequest request) {
            return base.Channel.Cliente_activo(request);
        }
        
        public string Cliente_activo(string user, string pass) {
            Vista.WEBServiceLogin.Cliente_activoRequest inValue = new Vista.WEBServiceLogin.Cliente_activoRequest();
            inValue.Body = new Vista.WEBServiceLogin.Cliente_activoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WEBServiceLogin.Cliente_activoResponse retVal = ((Vista.WEBServiceLogin.WSLOGIN)(this)).Cliente_activo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WEBServiceLogin.Cliente_activoResponse> Vista.WEBServiceLogin.WSLOGIN.Cliente_activoAsync(Vista.WEBServiceLogin.Cliente_activoRequest request) {
            return base.Channel.Cliente_activoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WEBServiceLogin.Cliente_activoResponse> Cliente_activoAsync(string user, string pass) {
            Vista.WEBServiceLogin.Cliente_activoRequest inValue = new Vista.WEBServiceLogin.Cliente_activoRequest();
            inValue.Body = new Vista.WEBServiceLogin.Cliente_activoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WEBServiceLogin.WSLOGIN)(this)).Cliente_activoAsync(inValue);
        }
    }
}
