//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONO_RESERVA
    {
        public ABONO_RESERVA()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int ID_ABONO_RESERVA { get; set; }
        public int VALOR_RESERVA { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_ESTADO { get; set; }
        public string HORA_ESTADO { get; set; }
        public string RUT_CLIENTE { get; set; }
        public int ID_METODO_PAGO { get; set; }
    
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
