//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public int VALOR { get; set; }
        public int CANTIDAD { get; set; }
        public int TOTAL { get; set; }
        public int ID_PEDIDO { get; set; }
    
        public virtual PEDIDO_PROVEEDOR PEDIDO_PROVEEDOR { get; set; }
    }
}
