//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION
    {
        public int ID { get; set; }
        public string RUT_CLIENTE { get; set; }
        public Nullable<int> MESA { get; set; }
        public string ESTADO { get; set; }
        public string FECHA { get; set; }
        public string HORA_INGRESO { get; set; }
        public string HORA_SALIDA { get; set; }
    }
}
