//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID_BOLETA { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public System.DateTime HORA_EMISION { get; set; }
        public Nullable<int> PROPINA { get; set; }
        public int IVA { get; set; }
        public int TOTAL_BOLETA { get; set; }
        public int SUB_TOTAL { get; set; }
        public Nullable<int> DESCUENTO { get; set; }
        public int PAGO { get; set; }
        public Nullable<int> VUELTO { get; set; }
        public Nullable<int> N_TRANSACCION { get; set; }
    
        public virtual PAGO PAGO1 { get; set; }
    }
}
