//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public CATEGORIA()
        {
            this.MENU = new HashSet<MENU>();
            this.PLATO = new HashSet<PLATO>();
        }
    
        public decimal ID_CATEGORIA { get; set; }
        public string NOMBRE_CAT { get; set; }
    
        public virtual ICollection<MENU> MENU { get; set; }
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
