//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGRESO
    {
        public int ID_EGRESO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string HORA { get; set; }
        public string ESTADO { get; set; }
        public int MONTO { get; set; }
        public string ID_PEDIDO { get; set; }
    
        public virtual PEDIDO_PROVEEDOR PEDIDO_PROVEEDOR { get; set; }
    }
}
