//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDAD_BANCARIA
    {
        public ENTIDAD_BANCARIA()
        {
            this.METODO_PAGO = new HashSet<METODO_PAGO>();
        }
    
        public int ID_ENTIDAD { get; set; }
        public string NOMBRE_BANCO { get; set; }
        public string DESCRIPCION_BANCO { get; set; }
        public int NRO_CUENTA { get; set; }
        public string TIPO_CTA { get; set; }
    
        public virtual ICollection<METODO_PAGO> METODO_PAGO { get; set; }
    }
}
