//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRA
    {
        public int ID_EXTRA { get; set; }
        public System.DateTime FECHA_EXTRA { get; set; }
        public string HORA_EXTRA { get; set; }
        public int CANTIDAD_EXTRA { get; set; }
        public int TOTAL_EXTRA { get; set; }
        public string ESTADO { get; set; }
        public int ID_BEBIDA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string RUT_EMPLEADO { get; set; }
        public Nullable<int> ID_ORDEN { get; set; }
    
        public virtual BEBIDA BEBIDA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ORDEN ORDEN { get; set; }
    }
}
