//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public int ID_MENU { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public int PRECIO { get; set; }
        public byte[] FOTO { get; set; }
        public int ID_BEBIDA { get; set; }
        public int ID_PLATO { get; set; }
        public int ID_CATEGORIA { get; set; }
    
        public virtual BEBIDA BEBIDA { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual PLATO PLATO { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
    }
}
