//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int NUM_MESA { get; set; }
        public System.DateTime FECHA_DISPONIBILIDAD_MESA { get; set; }
        public System.DateTime HORA_DISPONIBILIDAD_MESA { get; set; }
        public int CAPACIDAD_PERSONA { get; set; }
        public string RUT_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
