//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class METODO_PAGO
    {
        public METODO_PAGO()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public int ID_METODO_PAGO { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> ID_ENTIDAD { get; set; }
    
        public virtual ENTIDAD_BANCARIA ENTIDAD_BANCARIA { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
