//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RSXXI_Entities : DbContext
    {
        public RSXXI_Entities()
            : base("name=RSXXI_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENDA> AGENDA { get; set; }
        public DbSet<ATENCION> ATENCION { get; set; }
        public DbSet<BEBIDA> BEBIDA { get; set; }
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ENTIDAD_BANCARIA> ENTIDAD_BANCARIA { get; set; }
        public DbSet<INGRESOS> INGRESOS { get; set; }
        public DbSet<LOGIN> LOGIN { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public DbSet<ORDEN> ORDEN { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PAGO_EXTERNO> PAGO_EXTERNO { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PEDIDO_PROVEEDOR> PEDIDO_PROVEEDOR { get; set; }
        public DbSet<PLATO> PLATO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<TIPO_BEBIDA> TIPO_BEBIDA { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
    }
}
