//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public ORDEN()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public int ID_ORDEN { get; set; }
        public string DETALLE_ORDEN { get; set; }
        public System.DateTime FECHA_ORDEN { get; set; }
        public System.DateTime HORA_ORDEN { get; set; }
        public int CANTIDAD_PRODUCTO { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string ESTADO_ORDEN { get; set; }
        public int VALOR_ORDEN { get; set; }
        public int ID_MENU { get; set; }
        public string RUT_EMPLEADO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual MENU MENU { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
