//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PROVEEDOR
    {
        public PEDIDO_PROVEEDOR()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
            this.EGRESO = new HashSet<EGRESO>();
        }
    
        public string ID_PEDIDO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
    
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        public virtual ICollection<EGRESO> EGRESO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
