//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PROVEEDOR
    {
        public int ID_PEDIDO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string OBSERVACIONES { get; set; }
        public int CANTIDAD_PRODUCTO { get; set; }
        public string ESTADO { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public int ID_PRODUCTO { get; set; }
        public string RUT_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
