//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.ORDEN = new HashSet<ORDEN>();
            this.PAGO = new HashSet<PAGO>();
        }
    
        public int ID_PEDIDO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string HORA_PEDIDO { get; set; }
        public int PROPINA { get; set; }
        public Nullable<int> DESCUENTO { get; set; }
        public int SUBTOTAL { get; set; }
        public int TOTAL_PEDIDO { get; set; }
        public string ESTADO_SOLICITUD { get; set; }
        public string RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
