//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO
    {
        public PLATO()
        {
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public int ID_PLATO { get; set; }
        public string NOM_PLATO { get; set; }
        public int PRECIO_PLATO { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] FOTO { get; set; }
        public int STOCK { get; set; }
        public int ID_RECETA { get; set; }
        public int ID_CATEGORIA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual RECETA RECETA { get; set; }
    }
}
