//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.PEDIDO_PROVEEDOR = new HashSet<PEDIDO_PROVEEDOR>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string NOM_PROVEEDOR { get; set; }
        public string APE_PAT_PROVEEDOR { get; set; }
        public string APE_MAT_PROVEEDOR { get; set; }
        public string CORREO_PROVEEDOR { get; set; }
        public decimal TELEFONO_PROVEEDOR { get; set; }
        public string DIRECCION_PROVEEDOR { get; set; }
    
        public virtual ICollection<PEDIDO_PROVEEDOR> PEDIDO_PROVEEDOR { get; set; }
    }
}
