//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.PLATO = new HashSet<PLATO>();
        }
    
        public decimal ID_RECETA { get; set; }
        public string NOM_RECETA { get; set; }
        public string INSTRUCCIONES { get; set; }
        public Nullable<decimal> TIEMPO_COCION { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string RUT_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<PLATO> PLATO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
