//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.PLATO = new HashSet<PLATO>();
        }
    
        public int ID_RECETA { get; set; }
        public string NOM_RECETA { get; set; }
        public string INSTRUCCIONES { get; set; }
        public string INGREDIENTES { get; set; }
        public Nullable<int> TIEMPO_COCCION { get; set; }
        public int TIEMPO_PREPARACION { get; set; }
        public int TIEMPO_TOTAL { get; set; }
        public int PORCION { get; set; }
    
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
