//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int ID_RESERVA { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public string HORA_RESERVA { get; set; }
        public int CANTIDAD_PERSONAS { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO_RESERVA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public int ID_AGENDA { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
